# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 37d0f0275b0d868a56bfe679dfdb3387a736289d31459efaaaf3b9cc87b90bd3b4e4d089a035b0cb049fe6e9865431425d8f0af0d3aec65f960f30f100d34afd

test:
  secret_key_base: 7a746eabfc9a66e4efb1f3acbd3450c3e09eadd79c4625738a13a7c0b2ca06a1d6992e2b2a0bee0a6df41e48d9deab9e43d8b0d629652a484af580b109b389f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
